acme_project/acme_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('birthday/', include('birthday.urls')),
]

acme_project/birthday/urls.py
from django.urls import path

from . import views

app_name = 'birthday'

urlpatterns = [
    path('', views.birthday, name='create'),
    path('list/', views.birthday_list, name='list'),
    path('<int:pk>/edit', views.birthday, name='edit'),
    path('<int:pk>/delete', views.delete_birthday, name='delete')
]

acme_project/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

acme_project/birthday/models.py
from django.db import models


class Birthday(models.Model):
    first_name = models.CharField('Имя', max_length=20)
    last_name = models.CharField(
        'Фамилия', blank=True, help_text='Необязательное поле', max_length=20
    )
    birthday = models.DateField('Дата рождения')

acme_project/birthday/forms.py
from django import forms
from .models import Birthday


class BirthdayForm(forms.ModelForm):
    class Meta:
        model = Birthday
        fields = '__all__'
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

acme_project/birthday/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .forms import BirthdayForm
from .models import Birthday
from .utils import calculate_birthday_countdown


def birthday(request, pk=None):
    if pk:
        instance = get_object_or_404(Birthday, pk=pk)
    else:
        instance = None

    form = BirthdayForm(request.POST or None, instance=instance)
    context = {'form': form}
    if form.is_valid():
        form.save()
        birthday_countdown = calculate_birthday_countdown(
            form.cleaned_data['birthday'])
        context.update({'birthday_countdown': birthday_countdown})
    return render(request, 'birthday/birthday.html', context)


def birthday_list(request):
    birthdays = Birthday.objects.all()
    context = {'birthdays': birthdays}
    return render(request, 'birthday/birthday_list.html', context)


def delete_birthday(request, pk):
    instance = get_object_or_404(Birthday, pk=pk)
    form = BirthdayForm(instance=instance)
    context = {'form': form}
    if request.method == 'POST':
        instance.delete()
        return redirect('/birthday:list')
    return render(request, 'birthday/birthday.html', context)

acme_project/pages/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'pages/index.html')

acme_project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>Проект ACME</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <div class="container pt-5">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

acme_project/templates/birthday/birthday.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit" in request.path %}
      <h1>Редактировать запись {{ data.pk }} </h2>
    {% elif "/delete" in request.path %}
      <h1>Удалить запись {{ data.pk }} </h1>
    {% else %}
      <h1>Создать запись</h1>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Калькулятор ожидания дня рождения
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if "/delete" in request.path %}
            <p>{{ data.first_name }} {{ data.last_name }}</p> <p>{{ data.birthday }}</p>
          {% else %}
            {% bootstrap_form form %}
          {% endif %}
          
          {% bootstrap_button button_type="submit" content="Oтправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
      ID новой записи в БД: {{ data.id }}
      <hr>
      <h2>Привет, {{ data.first_name }} {{ data.last_name }}</h2>
      {% if birthday_cooldown == 0 %}
        С днём рождения!
      {% else %}
        Осталось дней до дня рождения: {{ birthday_countdown }}!
      {% endif %}
    {% endif %}
  {% endwith %}
{% endblock %}

acme_project/templates/birthday/birthday_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% for birthday in birthdays %}
    <div>
      <div>
        {{ birthday.first_name }} {{ birthday.last_name }} - {{ birthday.birthday }}
      </div>
      <div>
        <a href="{% url 'birthday:edit' birthday.id %}">Изменить запись</a>
        <a href="{% url 'birthday:delete' birthday.id %}">Удалить запись</a>
      </div>
      {% if not forloop.last %} 
        <hr>
      {% endif %}
    </div>
  {% endfor %}
{% endblock %}

acme_project/templates/includes/header.html
<header>
  <nav class="navbar shadow-sm">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:homepage' %} active {% endif %}"
              href="{% url 'pages:homepage' %}">
              Главная
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'birthday:create' %} active {% endif %}"
              href="{% url 'birthday:create' %}">
              Калькулятор дней рождения
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'birthday:list' %} active {% endif %}"
              href="{% url 'birthday:list' %}">
              Список дней рождения
            </a>
          </li>
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

acme_project/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Проект ACME</h1>
  <p>Acme Corporation: <b>A</b> <b>C</b>ompany <b>M</b>ade <b>E</b>verything</p>
{% endblock %}